### ISSUE TITLE
Runners.sol migrated to VRF2.5

### ISSUE THREAD

**Issue by zeluizgo** [solangegueiros/chainlink-bootcamp-2024#2]
Sol, fiz seu bootcamp (enviei o formulário completinho preenchido..espero meu certificado...rs) .. mas para fazer a aula 08 tive de migrar o  código Runners para a versão 2.5, onde o subscriptionid aumentou de tamanho para o uint256 ao inves do uint64.
salvei o codigo aqui no git... se quiser me colocar como contribuidor e eu mudo direto aí no seu .. ou se quiser copiar lá do meu ..vc pode até comparar no hiostórico qual foi a diferença.
Segue o link: https://github.com/zeluizgo/chainlink1stbootcamp/blob/main/Runners.sol

No que precisar estou a disposição vc e e seu bootcamp são nota dez! muito obrigado.

**Comment by solangegueiros** [comment]
Ola 
Muito obrigada pela ajuda!

No final eu atualizei o codigo sozinha, porque eu precisava atualizar os links e tambem eu queria manter o saldo da conta do VRF em LINK, nao em token nativo.
Mas a base foi o seu cofigo, ajudou muito!
